name: Maven Package

on:
  release:
    types: [created]

  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
  
    - name: Download
      run : wget http://geosiris.com/wp-content/uploads/2022/09/resqml_v2.0.1.zip -P ${{ github.workspace }}

    - name: Unzip
      run: 7z x ${GITHUB_WORKSPACE}/resqml_v2.0.1.zip -o${{ github.workspace }}/src/main/xsd/energyml/resqml/

    - name: Write settings 
      uses: s4u/maven-settings-action@v2.6.0
      with:
        properties: '[{"source": "src/main/xsd/energyml/resqml/v2.0.1/xsd_schemas/ResqmlAllObjects.xsd"}]'
        
    - name: Content list 1
      run: ls ${{ github.workspace }}/src/main/xsd/energyml/resqml/v2.0.1
    - name: Content list 2
      run: ls ${{ github.workspace }}/src/main/xsd/energyml/resqml/v2.0.1/xsd_schemas/
