name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
  
    - name: Download
      uses: wei/wget@v1
      with:
        args: http://geosiris.com/wp-content/uploads/2022/09/resqml_v2.0.1.zip

    - name: Unzip
      uses: montudor/action-zip@v1
      with:
        args: unzip -qq resqml_v2.0.1.zip -d /src/main/xsd/energyml/resqml/v2.0.1

    - name: Write settings 
      uses: s4u/maven-settings-action@v2.6.0
      with:
        properties: '[{"source": "src/main/xsd/energyml/resqml/v2.0.1/xsd_schemas/ResqmlAllObjects.xsd"}]'
        
    - name: Content list
      # You may pin to the exact commit or the version.
      # uses: enricomarino/actions@cc077a8a196155a9d5dc6ebcd3ff2c8a8679506f
      uses: enricomarino/actions@v2
      with:
        # The folder to inspect
        source: /src/main/xsd/energyml/resqml/v2.0.1
