name: Maven Package

on:
  release:
    types: [created]

  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
          
    - name: Download COMMON v2.0
      run : wget http://geosiris.com/wp-content/uploads/2022/09/common_v2.0.zip -P ${{ github.workspace }}
  
    - name: Unzip COMMON v2.0
      run: 7z x ${GITHUB_WORKSPACE}/common_v2.0.zip -o${{ github.workspace }}/src/main/xsd/energyml/common/
      
    - name: Download RESQML v2.0.1
      run : wget http://geosiris.com/wp-content/uploads/2022/09/resqml_v2.0.1.zip -P ${{ github.workspace }}

    - name: Unzip RESQML v2.0.1
      run: 7z x ${GITHUB_WORKSPACE}/resqml_v2.0.1.zip -o${{ github.workspace }}/src/main/xsd/energyml/resqml/
        
    # - name: Verify with Maven
    #   run: mvn -B verify -e -V --file pom.xml
    #   env:
    #     PATH_TO_SCHEMAS: ${{ github.workspace }}/src/main/xsd/energyml/resqml/v2.0.1/xsd_schemas/ResqmlAllObjects.xsd
    #     PKG_NAME: resqml
    #     PKG_VERSION: 201
    - name: build artifact
        run: mvn clean package
    - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "${{ github.workspace }}/target/*.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build with Maven
      run: mvn -B --no-transfer-progress --file pom.xml deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        PATH_TO_SCHEMAS: ${{ github.workspace }}/src/main/xsd/energyml/resqml/v2.0.1/xsd_schemas/ResqmlAllObjects.xsd
        PATH_TO_XJB: ${{ github.workspace }}/src/main/xjb/binding-resqml2_0_1.xjb
        PKG_NAME: resqml
        PKG_VERSION: 201
        PKG_VERSION_DOT: "2.0.1"
        COMMON_VERSION_DOT: "2.0"
      
