name: Maven Package Witsml v2.1

on:
  release:
    types: [created]

  # pull_request:
  #   branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - id: install-secret-key
      name: Install gpg secret key
      run: cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import

    - name: Download COMMON v2.3
      run : wget http://geosiris.com/wp-content/uploads/2022/09/common_v2.3.zip -P ${{ github.workspace }}
  
    - name: Unzip COMMON v2.3
      run: 7z x ${GITHUB_WORKSPACE}/common_v2.3.zip -o${{ github.workspace }}/src/main/xsd/energyml/common/
      
    - name: Download WITSML v2.1
      run : wget http://geosiris.com/wp-content/uploads/2022/09/witsml_v2.1.zip -P ${{ github.workspace }}

    - name: Unzip WITSML v2.1
      run: 7z x ${GITHUB_WORKSPACE}/witsml_v2.1.zip -o${{ github.workspace }}/src/main/xsd/energyml/witsml/

    - name: Build with Maven
      run: mvn -B --file pom.xml clean deploy -P release
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        PATH_TO_SCHEMAS: ${{ github.workspace }}/src/main/xsd/energyml/witsml/v2.1/xsd_schemas/WitsmlAllObjects.xsd
        PATH_TO_XJB: ${{ github.workspace }}/src/main/xjb/binding-witsml2_1.xjb
        PKG_NAME: witsml
        PKG_VERSION: 21
        RENAME_SCRIPT_ARG: "common::2.3 witsml::2.1"
